version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: clase-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: clase
    volumes:
      - clase-data:/var/lib/mysql
    networks:
      - clase-net

  api:
    build: .
    container_name: clase_api
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - clase-net
    volumes:
      - .:/app

volumes:
  clase-data:

networks:
  clase-net:
