services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clase123
      MYSQL_DATABASE: bd_clase
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: clase123
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - entrega3net

  entrega3app:
    build: .
    container_name: entrega3app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mariadb+mariadbconnector://fastapi_user:clase123@db:3306/bd_clase'
    command: >
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8080"
    volumes:
      - .:/app
    networks:
      - entrega3net

volumes:
  mariadb-data:

networks:
  entrega3net:
